export const URL_SPEED_IGNORE = [
  'aegis.qq.com',
  'tamaegis.com',
  '/aegis-sdk',
  'rumt-',
  '/flog.core.min.js',
  'pingfore.qq.com/pingd',
  'h.trace.qq.com',
  'btrace.qq.com',
  'beacon.qq.com',
  'dmplog.qq.com',
  'qq.com/report',
  'pcmgrmonitor.3g.qq.com',
  'report.qqweb.qq.com',
  'tpstelemetry.tencent.com',
  'insight.cloud.tencent.com',
  'www.googletagmanager.com',
  'report.idqqimg.com',
  'google-analytics.com',
  'arms-retcode.aliyuncs.com',
  'px.effirst.com',
  'sentry',
  'hot-update.json',
  'u.c.b.r.o.w.s.e.r',
  'report.url.cn',
  'sockjs-node',
];

export const ERROR_MSG_IGNORE = [
  'ResizeObserver loop limit exceeded',
  'Failed to execute \'transaction\'',
  'window.indexedDB.deleteDatabase is not a function',
];
